Meal_Plan/urls.py
from django.urls import path


from Meal_Plan.views import (
    MealPlanCreateView,
    MealPlanDeleteView,
    MealPlanUpdateView,
    MealPlanDetailView,
    MealPlanListView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="MealPlan_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="MealPlan_detail"),
    path(
        "<int:pk>/delete/",
        MealPlanDeleteView.as_view(), name="MealPlan_delete"),

    path(
        "create/",
        MealPlanCreateView.as_view(), name="MealPlan_create"),

    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="MealPlan_edit"),

]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("Meal_Plan/", include("Meal_Plan.urls"), name="Meal_Plan"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

Meal_Plan/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField("%B %d, %Y")
    owner = models.ForeignKey(
        USER_MODEL,
        on_delete=models.CASCADE,
        related_name="user_meal_plans",
        null=True,
    )
    recipes = models.ManyToManyField(
        "recipes.Recipe", related_name="MealPlan"
    )


def __str__(self):
    return self.name + " by " + str(self.owner)

Meal_Plan/views.py
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from Meal_Plan.models import MealPlan


class MealPlanListView(ListView):
    model = MealPlan
    template_name = "Meal_Plan/list.html"
    paginate_by = 2

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "Meal_Plan/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "Meal_Plan/new.html"
    fields = ["name", "date", "owner", "recipes"]
    # success_url = reverse_lazy("MealPlan_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("MealPlan_list")


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "Meal_Plan/edit.html"
    fields = ["name", "date", "owner", "recipes"]
    success_url = reverse_lazy("MealPlan_edit")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self) -> str:
        return reverse_lazy("MealPlan_edit", args=[self.object.id])


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "Meal_Plan/delete.html"
    success_url = reverse_lazy("MealPlan_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

Meal_Plan/templates/Meal_Plan/delete.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
  <main>
    <div class="delete-form">
      <form method="post">
        {% csrf_token %}
        <h3>Are you sure you want to delete "{{ MealPlan.name }}"?</h3>
        {{ form.as_p }}
        <div>
          <button class="button">Delete</button>
        </div>
      </form>
    </div>
  </main>
{% endblock content %}

Meal_Plan/templates/Meal_Plan/detail.html
{% extends 'base.html' %}
{% load markdownify %}
{% load static %}

{% block content %}
  <main class="recipes-detail">
    <div>
      <a href="{% url 'MealPlan_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'MealPlan_delete' mealplan.id %}">Delete</a>
    </div>
    <h2> Meal Plan for {{ user }} on Sep.1 2022</h2>
    {% for recipe in mealplan.recipes.all %}
      <p>
        <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
      </p>
    {% endfor %}
  </main>
{% endblock content %}

Meal_Plan/templates/Meal_Plan/edit.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
  <main class="MealPlan-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Update</button>
      </div>
    </form>
  </main>
{% endblock content %}

Meal_Plan/templates/Meal_Plan/list.html
{% extends 'base.html' %}
{% load markdownify %}

{% block pagination %}
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
{% endblock pagination %}

{% block content %}
<a href="{% url 'MealPlan_create' %}">create</a>
  <main class="recipe-grid">
    {% for MealPlan in mealplan_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'MealPlan_detail' MealPlan.pk %}">{{ MealPlan.name }}</a>
        </h2>
          <p>
            {% for recipe in MealPlan.recipes.all %}
            <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
          </p>
        {% endfor %}
      </div>
    {% empty %}
      <div>
        <h1>No Meal Plan?</h1>
        <p>
          Would you like to
          <a href="{% url 'MealPlan_create' %}">create</a>
          one?
        </p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

Meal_Plan/templates/Meal_Plan/new.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
  <main class="MealPlan-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main>
{% endblock content %}